### PR TITLE
Searching for .rubocop.yml on Home folder and changed notifications colors

### PR DESCRIPTION
**Pull request by rfocosi**
Change log:
-  Adding a `$HOME/.rubocop.yml` will work too now! It will first search on current project's root folder and after at $HOME;
- Changed notifications colors to show what were fixed after running Rubocop;

### CODE REVIEW

**Comment by tomoya** [comment]
Hi @rfocosi,

Thank you for your great pull-request! I am so happy.

BTW, I investigated a test to fail. But, I also could not find the cause. I think this pull-reqeust was not changed return value. So, I guess the test has no need to change.

Actually, I would like to merge this pull-request immediately. But, please give me time for investigation in this weekend.

Thank you,

**Comment by rfocosi** [comment]
Hi! I was investigating the test too.
I'm not good in this kind of specs, but I think something is wrong with the stubbed call. 
I'll let you know if I had some progress. 
Thank you!

**Comment by rfocosi** [comment]
Hi @tomoya!
I added a `buffer.reload()` on `autoCorretFile` success to fix the tests. I think makes sense to reload the buffer after the file was changed, anyway.

Also added a filter on rubocop command's call to remove any `--format` argument, because now the auto correct result uses the `--format json`

If you have any point on the implementation, I'm open to receive critics :)

Your package helps me a lot! 
Thank you again!

**Comment by tomoya** [comment]
Hi @rfocosi, awesome!
I could not notice to use `buffer.realod()`. I will be able to merge this branch without hesitation.
This pull-request is a perfect for me.

> Your package helps me a lot! 
> Thank you again!

My pleasure! Thank you,

**Pull request merged**
